version: "3.8"

services:
  mongodb:
    image: mongo 
    container_name: mongo 
    ports:
      - 27017:27017
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express 
    container_name: mongoui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin 
    ports:
      - 8081:8081
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge